apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: hello-world
    domain: examples
    service: hello_world
  name: hello-world
  namespace: platform
spec:
  replicas: 1
  progressDeadlineSeconds: 600
  template:
    metadata:
      labels:
        app: hello-world
        domain: examples
        service: hello_world
      namespace: platform
    spec:
      containers:
      - env:
        - name: BROKER_HOST
          valueFrom:
            configMapKeyRef:
              name: general-config
              key: broker.host
        - name: BROKER_PORT
          valueFrom:
            configMapKeyRef:
              name: general-config
              key: broker.port
        - name: BROKER_USER
          valueFrom:
            configMapKeyRef:
              name: general-config
              key: broker.user
        - name: BROKER_PASS
          valueFrom:
            secretKeyRef:
              name: general-secrets
              key: broker.password
        - name: JAVA_OPTS
          value: -Xmx128m -XX:+UseG1GC -Xss256K -Dservicemodel.logger.br.com.senior=INFO
        image: seniorsistemas/hello-world:{$version}
        name: hello-world
  revisionHistoryLimit: 3
